module.exports = {
    clearMocks: true,
    collectCoverage: true,
    coveragePathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '/src/lib/polyfill.js',
        '/src/third-party/',
        '/build/',
        '/coverage/',
        '/__mocks__/',
        '/.storybook/',
        '/src/lib/types/',
        '/src/lib/__tests__/',
    ],
    collectCoverageFrom: [
        'src/lib/**/*.{js,jsx,ts,tsx}',
        '!**/*-test.*',
        '!src/lib/browser.js',
        '!src/third-party/**',
        '!src/lib/viewers/box3d/model3d/Model3DAnimationClipsPullup.js',
        '!src/lib/viewers/box3d/model3d/model3DSettingsPullup.js',
        '!src/lib/viewers/box3d/model3d/Model3DVrControls.js',
        '!src/lib/viewers/box3d/**/SceneEntities.js',
        '!src/lib/viewers/box3d/**Constants.js',
    ],

    globals: {
        __NAME__: 'name',
        __VERSION__: 'version',
        __LANGUAGE__: 'en-US',
    },
    moduleFileExtensions: ['js', 'jsx', 'json', 'ts', 'tsx'],

    moduleNameMapper: {
        '\\.(css|scss|less)$': '<rootDir>/build/jest/styleMock.js',
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2)$': '<rootDir>/build/jest/fileMock.js',
        '@box/react-virtualized/dist/es': '@box/react-virtualized/dist/commonjs',
        'box-elements-messages': '<rootDir>/build/jest/i18nMock.js',
        'react-intl': '<rootDir>/build/jest/react-intl-mock.js',
        THREE: '<rootDir>/src/third-party/model3d/1.12.0/three.min.js',
    },
    restoreMocks: true,
    roots: ['src'],
    setupFiles: [
        '<rootDir>/src/lib/types/jest-global.d.ts',
        '<rootDir>/build/jest/envGlobals.js',
        '<rootDir>/build/jest/envWindow.js',
        'jest-canvas-mock',
        'mock-local-storage',
    ],
    setupFilesAfterEnv: ['<rootDir>/build/jest/envSetup.js'],
    testPathIgnorePatterns: ['node_modules', 'dist', '__mocks__'],
    transform: {
        '^.+\\.[jt]sx?$': 'babel-jest',
        '^.+\\.(svg|html)$': '<rootDir>/build/jest/stringLoader.js',
    },
    transformIgnorePatterns: ['node_modules/(?!(box-ui-elements|react-virtualized)/)'],
};
